/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Promotion = {
  _id: string;
  _type: "promotion";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  internalTitle?: string;
  promotion_text?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2";
        listItem?: never;
        markDefs?: Array<{
          hex?:
            | "#e11d48"
            | "#800000"
            | "#fef2f2"
            | "#fee2e2"
            | "#fecaca"
            | "#fca5a5"
            | "#f87171"
            | "#ef4444"
            | "#dc2626"
            | "#b91c1c"
            | "#991b1b"
            | "#7f1d1d"
            | "#450a0a"
            | "#fff7ed"
            | "#ffedd5"
            | "#fed7aa"
            | "#fdba74"
            | "#fb923c"
            | "#f97316"
            | "#ea580c"
            | "#c2410c"
            | "#9a3412"
            | "#7c2d12"
            | "#431407"
            | "#fffbeb"
            | "#fef3c7"
            | "#fde68a"
            | "#fcd34d"
            | "#fbbf24"
            | "#f59e0b"
            | "#d97706"
            | "#b45309"
            | "#92400e"
            | "#78350f"
            | "#451a03"
            | "#fefce8"
            | "#fef9c3"
            | "#fef08a"
            | "#fde047"
            | "#facc15"
            | "#eab308"
            | "#ca8a04"
            | "#a16207"
            | "#854d0e"
            | "#713f12"
            | "#422006"
            | "#f7fee7"
            | "#ecfccb"
            | "#d9f99d"
            | "#bef264"
            | "#a3e635"
            | "#84cc16"
            | "#65a30d"
            | "#4d7c0f"
            | "#3f6212"
            | "#365314"
            | "#1a2e05"
            | "#f0fdf4"
            | "#dcfce7"
            | "#bbf7d0"
            | "#86efac"
            | "#4ade80"
            | "#22c55e"
            | "#16a34a"
            | "#15803d"
            | "#166534"
            | "#14532d"
            | "#052e16"
            | "#ecfdf5"
            | "#d1fae5"
            | "#a7f3d0"
            | "#6ee7b7"
            | "#34d399"
            | "#10b981"
            | "#059669"
            | "#047857"
            | "#065f46"
            | "#064e3b"
            | "#022c22"
            | "#f0fdfa"
            | "#ccfbf1"
            | "#99f6e4"
            | "#5eead4"
            | "#2dd4bf"
            | "#14b8a6"
            | "#0d9488"
            | "#0f766e"
            | "#115e59"
            | "#134e4a"
            | "#042f2e"
            | "#ecfeff"
            | "#cffafe"
            | "#a5f3fc"
            | "#67e8f9"
            | "#22d3ee"
            | "#06b6d4"
            | "#0891b2"
            | "#0e7490"
            | "#155e75"
            | "#164e63"
            | "#083344"
            | "#f0f9ff"
            | "#e0f2fe"
            | "#bae6fd"
            | "#7dd3fc"
            | "#38bdf8"
            | "#0ea5e9"
            | "#0284c7"
            | "#0369a1"
            | "#075985"
            | "#0c4a6e"
            | "#082f49"
            | "#eff6ff"
            | "#dbeafe"
            | "#bfdbfe"
            | "#93c5fd"
            | "#60a5fa"
            | "#3b82f6"
            | "#2563eb"
            | "#1d4ed8"
            | "#1e40af"
            | "#1e3a8a"
            | "#172554"
            | "#eef2ff"
            | "#e0e7ff"
            | "#c7d2fe"
            | "#a5b4fc"
            | "#818cf8"
            | "#6366f1"
            | "#4f46e5"
            | "#4338ca"
            | "#3730a3"
            | "#312e81"
            | "#1e1b4b"
            | "#f5f3ff"
            | "#ede9fe"
            | "#ddd6fe"
            | "#c4b5fd"
            | "#a78bfa"
            | "#8b5cf6"
            | "#7c3aed"
            | "#6d28d9"
            | "#5b21b6"
            | "#4c1d95"
            | "#2e1065"
            | "#faf5ff"
            | "#f3e8ff"
            | "#e9d5ff"
            | "#d8b4fe"
            | "#c084fc"
            | "#a855f7"
            | "#9333ea"
            | "#7e22ce"
            | "#6b21a8"
            | "#581c87"
            | "#3b0764"
            | "#fdf4ff"
            | "#fae8ff"
            | "#f5d0fe"
            | "#f0abfc"
            | "#e879f9"
            | "#d946ef"
            | "#c026d3"
            | "#a21caf"
            | "#86198f"
            | "#701a75"
            | "#4a044e"
            | "#fdf2f8"
            | "#fce7f3"
            | "#fbcfe8"
            | "#f9a8d4"
            | "#f472b6"
            | "#ec4899"
            | "#db2777"
            | "#be185d"
            | "#9d174d"
            | "#831843"
            | "#500724"
            | "#fff1f2"
            | "#ffe4e6"
            | "#fecdd3"
            | "#fda4af"
            | "#fb7185"
            | "#f43f5e"
            | "#e11d48"
            | "#be123c"
            | "#9f1239"
            | "#881337"
            | "#4c0519"
            | "#f8fafc"
            | "#f1f5f9"
            | "#e2e8f0"
            | "#cbd5e1"
            | "#94a3b8"
            | "#64748b"
            | "#475569"
            | "#334155"
            | "#1e293b"
            | "#0f172a"
            | "#020617";
          _type: "color";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  image_background?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  cta_text?: string;
  cta_background?:
    | "#e11d48"
    | "#800000"
    | "#fef2f2"
    | "#fee2e2"
    | "#fecaca"
    | "#fca5a5"
    | "#f87171"
    | "#ef4444"
    | "#dc2626"
    | "#b91c1c"
    | "#991b1b"
    | "#7f1d1d"
    | "#450a0a"
    | "#fff7ed"
    | "#ffedd5"
    | "#fed7aa"
    | "#fdba74"
    | "#fb923c"
    | "#f97316"
    | "#ea580c"
    | "#c2410c"
    | "#9a3412"
    | "#7c2d12"
    | "#431407"
    | "#fffbeb"
    | "#fef3c7"
    | "#fde68a"
    | "#fcd34d"
    | "#fbbf24"
    | "#f59e0b"
    | "#d97706"
    | "#b45309"
    | "#92400e"
    | "#78350f"
    | "#451a03"
    | "#fefce8"
    | "#fef9c3"
    | "#fef08a"
    | "#fde047"
    | "#facc15"
    | "#eab308"
    | "#ca8a04"
    | "#a16207"
    | "#854d0e"
    | "#713f12"
    | "#422006"
    | "#f7fee7"
    | "#ecfccb"
    | "#d9f99d"
    | "#bef264"
    | "#a3e635"
    | "#84cc16"
    | "#65a30d"
    | "#4d7c0f"
    | "#3f6212"
    | "#365314"
    | "#1a2e05"
    | "#f0fdf4"
    | "#dcfce7"
    | "#bbf7d0"
    | "#86efac"
    | "#4ade80"
    | "#22c55e"
    | "#16a34a"
    | "#15803d"
    | "#166534"
    | "#14532d"
    | "#052e16"
    | "#ecfdf5"
    | "#d1fae5"
    | "#a7f3d0"
    | "#6ee7b7"
    | "#34d399"
    | "#10b981"
    | "#059669"
    | "#047857"
    | "#065f46"
    | "#064e3b"
    | "#022c22"
    | "#f0fdfa"
    | "#ccfbf1"
    | "#99f6e4"
    | "#5eead4"
    | "#2dd4bf"
    | "#14b8a6"
    | "#0d9488"
    | "#0f766e"
    | "#115e59"
    | "#134e4a"
    | "#042f2e"
    | "#ecfeff"
    | "#cffafe"
    | "#a5f3fc"
    | "#67e8f9"
    | "#22d3ee"
    | "#06b6d4"
    | "#0891b2"
    | "#0e7490"
    | "#155e75"
    | "#164e63"
    | "#083344"
    | "#f0f9ff"
    | "#e0f2fe"
    | "#bae6fd"
    | "#7dd3fc"
    | "#38bdf8"
    | "#0ea5e9"
    | "#0284c7"
    | "#0369a1"
    | "#075985"
    | "#0c4a6e"
    | "#082f49"
    | "#eff6ff"
    | "#dbeafe"
    | "#bfdbfe"
    | "#93c5fd"
    | "#60a5fa"
    | "#3b82f6"
    | "#2563eb"
    | "#1d4ed8"
    | "#1e40af"
    | "#1e3a8a"
    | "#172554"
    | "#eef2ff"
    | "#e0e7ff"
    | "#c7d2fe"
    | "#a5b4fc"
    | "#818cf8"
    | "#6366f1"
    | "#4f46e5"
    | "#4338ca"
    | "#3730a3"
    | "#312e81"
    | "#1e1b4b"
    | "#f5f3ff"
    | "#ede9fe"
    | "#ddd6fe"
    | "#c4b5fd"
    | "#a78bfa"
    | "#8b5cf6"
    | "#7c3aed"
    | "#6d28d9"
    | "#5b21b6"
    | "#4c1d95"
    | "#2e1065"
    | "#faf5ff"
    | "#f3e8ff"
    | "#e9d5ff"
    | "#d8b4fe"
    | "#c084fc"
    | "#a855f7"
    | "#9333ea"
    | "#7e22ce"
    | "#6b21a8"
    | "#581c87"
    | "#3b0764"
    | "#fdf4ff"
    | "#fae8ff"
    | "#f5d0fe"
    | "#f0abfc"
    | "#e879f9"
    | "#d946ef"
    | "#c026d3"
    | "#a21caf"
    | "#86198f"
    | "#701a75"
    | "#4a044e"
    | "#fdf2f8"
    | "#fce7f3"
    | "#fbcfe8"
    | "#f9a8d4"
    | "#f472b6"
    | "#ec4899"
    | "#db2777"
    | "#be185d"
    | "#9d174d"
    | "#831843"
    | "#500724"
    | "#fff1f2"
    | "#ffe4e6"
    | "#fecdd3"
    | "#fda4af"
    | "#fb7185"
    | "#f43f5e"
    | "#e11d48"
    | "#be123c"
    | "#9f1239"
    | "#881337"
    | "#4c0519"
    | "#f8fafc"
    | "#f1f5f9"
    | "#e2e8f0"
    | "#cbd5e1"
    | "#94a3b8"
    | "#64748b"
    | "#475569"
    | "#334155"
    | "#1e293b"
    | "#0f172a"
    | "#020617";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  brand?: string;
  stripePriceId?: string;
  displayPrice?: number;
  stock?: number;
  sku?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  catalogueLocationKeys?: Array<string>;
  overviewFields?: Array<{
    title?: string;
    value?: string;
    information?: string;
    _type: "overviewField";
    _key: string;
  }>;
  specifications?: Array<{
    title?: string;
    value?: string;
    information?: string;
    _type: "spec";
    _key: string;
  }>;
};

export type Catalogue = {
  _id: string;
  _type: "catalogue";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  catalogue?: Array<
    {
      _key: string;
    } & CatalogueItem
  >;
};

export type CatalogueItem = {
  _type: "catalogueItem";
  title?: string;
  type?: "link" | "header";
  slug?: Slug;
  icon?: string;
  children?: Array<
    {
      _key: string;
    } & CatalogueItem
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | Promotion
  | Product
  | Catalogue
  | CatalogueItem
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/commercials/getCommercialHeroMain.ts
// Variable: GET_COMMERCIALS_HERO_MAIN
// Query: *[_type == "commercial" && feature == "hero-main" && defined(image.asset)]  | order(displayOrder asc) [0]  {    _id,    "image": image.asset->url + "?fm=webp&w=1200&q=55",    "blurDataURL": image.asset->url + "?w=20&h=20&blur=10&q=20",    text,    ctaLink,    sale-> {      discount,      validUntil,      _id    }  }
export type GET_COMMERCIALS_HERO_MAINResult = null;

// Source: ./sanity/lib/commercials/getCommercialsByFeature.ts
// Variable: GET_COMMERCIALS_BY_FEATURE_QUERY
// Query: *[_type == "commercial" && feature == $feature] | order(displayOrder asc) {    _id,    title,    "image": image.asset->url,    variant,    displayOrder,    text,    ctaLink,    "products": products[]-> {      _id,      brand,      name,      description,      price,      "image": image.asset->url,    },    sale-> {      discount,      validUntil,      _id    }  }
export type GET_COMMERCIALS_BY_FEATURE_QUERYResult = Array<never>;

// Source: ./sanity/lib/commercials/getCommercialsHeroSecondary.ts
// Variable: GET_COMMERCIALS_HERO_SECONDARY
// Query: *[_type == "commercial" && feature == "hero-secondary" && defined(image.asset)] | order(displayOrder asc) {    _id,    title,    "image": image.asset->url,    variant,    displayOrder,    text,    ctaLink,    "products": products[]-> {      _id,      brand,      name,      description,      price,      "image": image.asset->url,    },    sale-> {      discount,      validUntil,      _id    }  }
export type GET_COMMERCIALS_HERO_SECONDARYResult = Array<never>;

// Source: ./sanity/lib/products/filter/getFilters.ts
// Variable: FILTERS
// Query: {    "brands": array::unique(*[_type == "product"].brand->name)  }
export type FILTERSResult = {
  brands: Array<null>;
};

// Source: ./sanity/lib/products/filter/getFiltersForCategoryPath.ts
// Variable: FILTERS_BY_CATEGORY_QUERY
// Query: *[_type == "categoryFilters" && title == $topLevelCategory][0] {      title,      "filters": filters.filterItems[]{        name,        type,        options,        defaultValue,        min,        max,        isMinOnly,        step      },      "mappings": categoryMappings[path == $cleanPath]    }
export type FILTERS_BY_CATEGORY_QUERYResult = null;

// Source: ./sanity/lib/products/getAllProducts.ts
// Variable: ALL_PRODUCTS_QUERY
// Query: *[            _type == "product"        ] | order(name asc)
export type ALL_PRODUCTS_QUERYResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  brand?: string;
  stripePriceId?: string;
  displayPrice?: number;
  stock?: number;
  sku?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  catalogueLocationKeys?: Array<string>;
  overviewFields?: Array<{
    title?: string;
    value?: string;
    information?: string;
    _type: "overviewField";
    _key: string;
  }>;
  specifications?: Array<{
    title?: string;
    value?: string;
    information?: string;
    _type: "spec";
    _key: string;
  }>;
}>;

// Source: ./sanity/lib/products/getProductById.ts
// Variable: PRODUCT_BY_ID_QUERY
// Query: *[                _type == 'product'                && _id == $id            ] | order(name asc) [0]
export type PRODUCT_BY_ID_QUERYResult = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  brand?: string;
  stripePriceId?: string;
  displayPrice?: number;
  stock?: number;
  sku?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  catalogueLocationKeys?: Array<string>;
  overviewFields?: Array<{
    title?: string;
    value?: string;
    information?: string;
    _type: "overviewField";
    _key: string;
  }>;
  specifications?: Array<{
    title?: string;
    value?: string;
    information?: string;
    _type: "spec";
    _key: string;
  }>;
} | null;

// Source: ./sanity/lib/products/searchProductsByName.ts
// Variable: SEARCH_FOR_PRODUCTS_QUERY
// Query: *[        _type == "product"        && name match $searchParam    ] | order(name asc)
export type SEARCH_FOR_PRODUCTS_QUERYResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  brand?: string;
  stripePriceId?: string;
  displayPrice?: number;
  stock?: number;
  sku?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  catalogueLocationKeys?: Array<string>;
  overviewFields?: Array<{
    title?: string;
    value?: string;
    information?: string;
    _type: "overviewField";
    _key: string;
  }>;
  specifications?: Array<{
    title?: string;
    value?: string;
    information?: string;
    _type: "spec";
    _key: string;
  }>;
}>;

// Source: ./sanity/lib/products/sort/getSortablesForCategoryPath.ts
// Variable: SORTABLES_BY_CATEGORY_QUERY
// Query: *[_type == "categorySortables" && title == $topLevelCategory][0] {      title,      "sortOptions": sortOptions[]{        name,        displayName,        type,        field,        defaultDirection      },      "mappings": categoryMappings[path == $cleanPath]    }
export type SORTABLES_BY_CATEGORY_QUERYResult = null;

// Source: ./sanity/lib/profiles/fetchProfileByClerkId.ts
// Variable: FETCH_PROFILE_QUERY
// Query: *[_type == "userProfile" && clerkId == $clerkId][0] {      _id,      _type,      clerkId,      displayName,      primaryAddress {        streetAddress,        city,        state,        postalCode,        country      },      preferences {        receiveMarketingEmails,        darkMode,        savePaymentInfo      },      createdAt,      updatedAt    }
export type FETCH_PROFILE_QUERYResult = null;

// Source: ./sanity/lib/promotions/getPromotionByName.ts
// Variable: PROMOTION_BY_NAME_QUERY
// Query: *[_type == "promotion" && internalTitle == $name][0]  {      _id,     promotion_text,        cta_text,        cta_background,      "image_background": {        "src": image_background.asset->url,        "alt": image_background.alt,        "width": image_background.asset->metadata.dimensions.width,        "height": image_background.asset->metadata.dimensions.height,        "blurDataURL": image_background.asset->metadata.lqip      }    }
export type PROMOTION_BY_NAME_QUERYResult = {
  _id: string;
  promotion_text: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h1" | "h2" | "normal";
        listItem?: never;
        markDefs?: Array<{
          hex?:
            | "#020617"
            | "#022c22"
            | "#0284c7"
            | "#0369a1"
            | "#042f2e"
            | "#047857"
            | "#052e16"
            | "#059669"
            | "#064e3b"
            | "#065f46"
            | "#06b6d4"
            | "#075985"
            | "#082f49"
            | "#083344"
            | "#0891b2"
            | "#0c4a6e"
            | "#0d9488"
            | "#0e7490"
            | "#0ea5e9"
            | "#0f172a"
            | "#0f766e"
            | "#10b981"
            | "#115e59"
            | "#134e4a"
            | "#14532d"
            | "#14b8a6"
            | "#155e75"
            | "#15803d"
            | "#164e63"
            | "#166534"
            | "#16a34a"
            | "#172554"
            | "#1a2e05"
            | "#1d4ed8"
            | "#1e1b4b"
            | "#1e293b"
            | "#1e3a8a"
            | "#1e40af"
            | "#22c55e"
            | "#22d3ee"
            | "#2563eb"
            | "#2dd4bf"
            | "#2e1065"
            | "#312e81"
            | "#334155"
            | "#34d399"
            | "#365314"
            | "#3730a3"
            | "#38bdf8"
            | "#3b0764"
            | "#3b82f6"
            | "#3f6212"
            | "#422006"
            | "#431407"
            | "#4338ca"
            | "#450a0a"
            | "#451a03"
            | "#475569"
            | "#4a044e"
            | "#4ade80"
            | "#4c0519"
            | "#4c1d95"
            | "#4d7c0f"
            | "#4f46e5"
            | "#500724"
            | "#581c87"
            | "#5b21b6"
            | "#5eead4"
            | "#60a5fa"
            | "#6366f1"
            | "#64748b"
            | "#65a30d"
            | "#67e8f9"
            | "#6b21a8"
            | "#6d28d9"
            | "#6ee7b7"
            | "#701a75"
            | "#713f12"
            | "#78350f"
            | "#7c2d12"
            | "#7c3aed"
            | "#7dd3fc"
            | "#7e22ce"
            | "#7f1d1d"
            | "#800000"
            | "#818cf8"
            | "#831843"
            | "#84cc16"
            | "#854d0e"
            | "#86198f"
            | "#86efac"
            | "#881337"
            | "#8b5cf6"
            | "#92400e"
            | "#9333ea"
            | "#93c5fd"
            | "#94a3b8"
            | "#991b1b"
            | "#99f6e4"
            | "#9a3412"
            | "#9d174d"
            | "#9f1239"
            | "#a16207"
            | "#a21caf"
            | "#a3e635"
            | "#a5b4fc"
            | "#a5f3fc"
            | "#a78bfa"
            | "#a7f3d0"
            | "#a855f7"
            | "#b45309"
            | "#b91c1c"
            | "#bae6fd"
            | "#bbf7d0"
            | "#be123c"
            | "#be185d"
            | "#bef264"
            | "#bfdbfe"
            | "#c026d3"
            | "#c084fc"
            | "#c2410c"
            | "#c4b5fd"
            | "#c7d2fe"
            | "#ca8a04"
            | "#cbd5e1"
            | "#ccfbf1"
            | "#cffafe"
            | "#d1fae5"
            | "#d8b4fe"
            | "#d946ef"
            | "#d97706"
            | "#d9f99d"
            | "#db2777"
            | "#dbeafe"
            | "#dc2626"
            | "#dcfce7"
            | "#ddd6fe"
            | "#e0e7ff"
            | "#e0f2fe"
            | "#e11d48"
            | "#e2e8f0"
            | "#e879f9"
            | "#e9d5ff"
            | "#ea580c"
            | "#eab308"
            | "#ec4899"
            | "#ecfccb"
            | "#ecfdf5"
            | "#ecfeff"
            | "#ede9fe"
            | "#eef2ff"
            | "#ef4444"
            | "#eff6ff"
            | "#f0abfc"
            | "#f0f9ff"
            | "#f0fdf4"
            | "#f0fdfa"
            | "#f1f5f9"
            | "#f3e8ff"
            | "#f43f5e"
            | "#f472b6"
            | "#f59e0b"
            | "#f5d0fe"
            | "#f5f3ff"
            | "#f7fee7"
            | "#f87171"
            | "#f8fafc"
            | "#f97316"
            | "#f9a8d4"
            | "#facc15"
            | "#fae8ff"
            | "#faf5ff"
            | "#fb7185"
            | "#fb923c"
            | "#fbbf24"
            | "#fbcfe8"
            | "#fca5a5"
            | "#fcd34d"
            | "#fce7f3"
            | "#fda4af"
            | "#fdba74"
            | "#fde047"
            | "#fde68a"
            | "#fdf2f8"
            | "#fdf4ff"
            | "#fecaca"
            | "#fecdd3"
            | "#fed7aa"
            | "#fee2e2"
            | "#fef08a"
            | "#fef2f2"
            | "#fef3c7"
            | "#fef9c3"
            | "#fefce8"
            | "#ffe4e6"
            | "#ffedd5"
            | "#fff1f2"
            | "#fff7ed"
            | "#fffbeb";
          _type: "color";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  > | null;
  cta_text: string | null;
  cta_background:
    | "#020617"
    | "#022c22"
    | "#0284c7"
    | "#0369a1"
    | "#042f2e"
    | "#047857"
    | "#052e16"
    | "#059669"
    | "#064e3b"
    | "#065f46"
    | "#06b6d4"
    | "#075985"
    | "#082f49"
    | "#083344"
    | "#0891b2"
    | "#0c4a6e"
    | "#0d9488"
    | "#0e7490"
    | "#0ea5e9"
    | "#0f172a"
    | "#0f766e"
    | "#10b981"
    | "#115e59"
    | "#134e4a"
    | "#14532d"
    | "#14b8a6"
    | "#155e75"
    | "#15803d"
    | "#164e63"
    | "#166534"
    | "#16a34a"
    | "#172554"
    | "#1a2e05"
    | "#1d4ed8"
    | "#1e1b4b"
    | "#1e293b"
    | "#1e3a8a"
    | "#1e40af"
    | "#22c55e"
    | "#22d3ee"
    | "#2563eb"
    | "#2dd4bf"
    | "#2e1065"
    | "#312e81"
    | "#334155"
    | "#34d399"
    | "#365314"
    | "#3730a3"
    | "#38bdf8"
    | "#3b0764"
    | "#3b82f6"
    | "#3f6212"
    | "#422006"
    | "#431407"
    | "#4338ca"
    | "#450a0a"
    | "#451a03"
    | "#475569"
    | "#4a044e"
    | "#4ade80"
    | "#4c0519"
    | "#4c1d95"
    | "#4d7c0f"
    | "#4f46e5"
    | "#500724"
    | "#581c87"
    | "#5b21b6"
    | "#5eead4"
    | "#60a5fa"
    | "#6366f1"
    | "#64748b"
    | "#65a30d"
    | "#67e8f9"
    | "#6b21a8"
    | "#6d28d9"
    | "#6ee7b7"
    | "#701a75"
    | "#713f12"
    | "#78350f"
    | "#7c2d12"
    | "#7c3aed"
    | "#7dd3fc"
    | "#7e22ce"
    | "#7f1d1d"
    | "#800000"
    | "#818cf8"
    | "#831843"
    | "#84cc16"
    | "#854d0e"
    | "#86198f"
    | "#86efac"
    | "#881337"
    | "#8b5cf6"
    | "#92400e"
    | "#9333ea"
    | "#93c5fd"
    | "#94a3b8"
    | "#991b1b"
    | "#99f6e4"
    | "#9a3412"
    | "#9d174d"
    | "#9f1239"
    | "#a16207"
    | "#a21caf"
    | "#a3e635"
    | "#a5b4fc"
    | "#a5f3fc"
    | "#a78bfa"
    | "#a7f3d0"
    | "#a855f7"
    | "#b45309"
    | "#b91c1c"
    | "#bae6fd"
    | "#bbf7d0"
    | "#be123c"
    | "#be185d"
    | "#bef264"
    | "#bfdbfe"
    | "#c026d3"
    | "#c084fc"
    | "#c2410c"
    | "#c4b5fd"
    | "#c7d2fe"
    | "#ca8a04"
    | "#cbd5e1"
    | "#ccfbf1"
    | "#cffafe"
    | "#d1fae5"
    | "#d8b4fe"
    | "#d946ef"
    | "#d97706"
    | "#d9f99d"
    | "#db2777"
    | "#dbeafe"
    | "#dc2626"
    | "#dcfce7"
    | "#ddd6fe"
    | "#e0e7ff"
    | "#e0f2fe"
    | "#e11d48"
    | "#e2e8f0"
    | "#e879f9"
    | "#e9d5ff"
    | "#ea580c"
    | "#eab308"
    | "#ec4899"
    | "#ecfccb"
    | "#ecfdf5"
    | "#ecfeff"
    | "#ede9fe"
    | "#eef2ff"
    | "#ef4444"
    | "#eff6ff"
    | "#f0abfc"
    | "#f0f9ff"
    | "#f0fdf4"
    | "#f0fdfa"
    | "#f1f5f9"
    | "#f3e8ff"
    | "#f43f5e"
    | "#f472b6"
    | "#f59e0b"
    | "#f5d0fe"
    | "#f5f3ff"
    | "#f7fee7"
    | "#f87171"
    | "#f8fafc"
    | "#f97316"
    | "#f9a8d4"
    | "#facc15"
    | "#fae8ff"
    | "#faf5ff"
    | "#fb7185"
    | "#fb923c"
    | "#fbbf24"
    | "#fbcfe8"
    | "#fca5a5"
    | "#fcd34d"
    | "#fce7f3"
    | "#fda4af"
    | "#fdba74"
    | "#fde047"
    | "#fde68a"
    | "#fdf2f8"
    | "#fdf4ff"
    | "#fecaca"
    | "#fecdd3"
    | "#fed7aa"
    | "#fee2e2"
    | "#fef08a"
    | "#fef2f2"
    | "#fef3c7"
    | "#fef9c3"
    | "#fefce8"
    | "#ffe4e6"
    | "#ffedd5"
    | "#fff1f2"
    | "#fff7ed"
    | "#fffbeb"
    | null;
  image_background: {
    src: string | null;
    alt: null;
    width: number | null;
    height: number | null;
    blurDataURL: string | null;
  };
} | null;

// Source: ./sanity/lib/promotions/smallTest.ts
// Variable: SMALL_TEST
// Query: *[_type == "promotion"][0]
export type SMALL_TESTResult = {
  _id: string;
  _type: "promotion";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  internalTitle?: string;
  promotion_text?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h1" | "h2" | "normal";
        listItem?: never;
        markDefs?: Array<{
          hex?:
            | "#020617"
            | "#022c22"
            | "#0284c7"
            | "#0369a1"
            | "#042f2e"
            | "#047857"
            | "#052e16"
            | "#059669"
            | "#064e3b"
            | "#065f46"
            | "#06b6d4"
            | "#075985"
            | "#082f49"
            | "#083344"
            | "#0891b2"
            | "#0c4a6e"
            | "#0d9488"
            | "#0e7490"
            | "#0ea5e9"
            | "#0f172a"
            | "#0f766e"
            | "#10b981"
            | "#115e59"
            | "#134e4a"
            | "#14532d"
            | "#14b8a6"
            | "#155e75"
            | "#15803d"
            | "#164e63"
            | "#166534"
            | "#16a34a"
            | "#172554"
            | "#1a2e05"
            | "#1d4ed8"
            | "#1e1b4b"
            | "#1e293b"
            | "#1e3a8a"
            | "#1e40af"
            | "#22c55e"
            | "#22d3ee"
            | "#2563eb"
            | "#2dd4bf"
            | "#2e1065"
            | "#312e81"
            | "#334155"
            | "#34d399"
            | "#365314"
            | "#3730a3"
            | "#38bdf8"
            | "#3b0764"
            | "#3b82f6"
            | "#3f6212"
            | "#422006"
            | "#431407"
            | "#4338ca"
            | "#450a0a"
            | "#451a03"
            | "#475569"
            | "#4a044e"
            | "#4ade80"
            | "#4c0519"
            | "#4c1d95"
            | "#4d7c0f"
            | "#4f46e5"
            | "#500724"
            | "#581c87"
            | "#5b21b6"
            | "#5eead4"
            | "#60a5fa"
            | "#6366f1"
            | "#64748b"
            | "#65a30d"
            | "#67e8f9"
            | "#6b21a8"
            | "#6d28d9"
            | "#6ee7b7"
            | "#701a75"
            | "#713f12"
            | "#78350f"
            | "#7c2d12"
            | "#7c3aed"
            | "#7dd3fc"
            | "#7e22ce"
            | "#7f1d1d"
            | "#800000"
            | "#818cf8"
            | "#831843"
            | "#84cc16"
            | "#854d0e"
            | "#86198f"
            | "#86efac"
            | "#881337"
            | "#8b5cf6"
            | "#92400e"
            | "#9333ea"
            | "#93c5fd"
            | "#94a3b8"
            | "#991b1b"
            | "#99f6e4"
            | "#9a3412"
            | "#9d174d"
            | "#9f1239"
            | "#a16207"
            | "#a21caf"
            | "#a3e635"
            | "#a5b4fc"
            | "#a5f3fc"
            | "#a78bfa"
            | "#a7f3d0"
            | "#a855f7"
            | "#b45309"
            | "#b91c1c"
            | "#bae6fd"
            | "#bbf7d0"
            | "#be123c"
            | "#be185d"
            | "#bef264"
            | "#bfdbfe"
            | "#c026d3"
            | "#c084fc"
            | "#c2410c"
            | "#c4b5fd"
            | "#c7d2fe"
            | "#ca8a04"
            | "#cbd5e1"
            | "#ccfbf1"
            | "#cffafe"
            | "#d1fae5"
            | "#d8b4fe"
            | "#d946ef"
            | "#d97706"
            | "#d9f99d"
            | "#db2777"
            | "#dbeafe"
            | "#dc2626"
            | "#dcfce7"
            | "#ddd6fe"
            | "#e0e7ff"
            | "#e0f2fe"
            | "#e11d48"
            | "#e2e8f0"
            | "#e879f9"
            | "#e9d5ff"
            | "#ea580c"
            | "#eab308"
            | "#ec4899"
            | "#ecfccb"
            | "#ecfdf5"
            | "#ecfeff"
            | "#ede9fe"
            | "#eef2ff"
            | "#ef4444"
            | "#eff6ff"
            | "#f0abfc"
            | "#f0f9ff"
            | "#f0fdf4"
            | "#f0fdfa"
            | "#f1f5f9"
            | "#f3e8ff"
            | "#f43f5e"
            | "#f472b6"
            | "#f59e0b"
            | "#f5d0fe"
            | "#f5f3ff"
            | "#f7fee7"
            | "#f87171"
            | "#f8fafc"
            | "#f97316"
            | "#f9a8d4"
            | "#facc15"
            | "#fae8ff"
            | "#faf5ff"
            | "#fb7185"
            | "#fb923c"
            | "#fbbf24"
            | "#fbcfe8"
            | "#fca5a5"
            | "#fcd34d"
            | "#fce7f3"
            | "#fda4af"
            | "#fdba74"
            | "#fde047"
            | "#fde68a"
            | "#fdf2f8"
            | "#fdf4ff"
            | "#fecaca"
            | "#fecdd3"
            | "#fed7aa"
            | "#fee2e2"
            | "#fef08a"
            | "#fef2f2"
            | "#fef3c7"
            | "#fef9c3"
            | "#fefce8"
            | "#ffe4e6"
            | "#ffedd5"
            | "#fff1f2"
            | "#fff7ed"
            | "#fffbeb";
          _type: "color";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  image_background?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  cta_text?: string;
  cta_background?:
    | "#020617"
    | "#022c22"
    | "#0284c7"
    | "#0369a1"
    | "#042f2e"
    | "#047857"
    | "#052e16"
    | "#059669"
    | "#064e3b"
    | "#065f46"
    | "#06b6d4"
    | "#075985"
    | "#082f49"
    | "#083344"
    | "#0891b2"
    | "#0c4a6e"
    | "#0d9488"
    | "#0e7490"
    | "#0ea5e9"
    | "#0f172a"
    | "#0f766e"
    | "#10b981"
    | "#115e59"
    | "#134e4a"
    | "#14532d"
    | "#14b8a6"
    | "#155e75"
    | "#15803d"
    | "#164e63"
    | "#166534"
    | "#16a34a"
    | "#172554"
    | "#1a2e05"
    | "#1d4ed8"
    | "#1e1b4b"
    | "#1e293b"
    | "#1e3a8a"
    | "#1e40af"
    | "#22c55e"
    | "#22d3ee"
    | "#2563eb"
    | "#2dd4bf"
    | "#2e1065"
    | "#312e81"
    | "#334155"
    | "#34d399"
    | "#365314"
    | "#3730a3"
    | "#38bdf8"
    | "#3b0764"
    | "#3b82f6"
    | "#3f6212"
    | "#422006"
    | "#431407"
    | "#4338ca"
    | "#450a0a"
    | "#451a03"
    | "#475569"
    | "#4a044e"
    | "#4ade80"
    | "#4c0519"
    | "#4c1d95"
    | "#4d7c0f"
    | "#4f46e5"
    | "#500724"
    | "#581c87"
    | "#5b21b6"
    | "#5eead4"
    | "#60a5fa"
    | "#6366f1"
    | "#64748b"
    | "#65a30d"
    | "#67e8f9"
    | "#6b21a8"
    | "#6d28d9"
    | "#6ee7b7"
    | "#701a75"
    | "#713f12"
    | "#78350f"
    | "#7c2d12"
    | "#7c3aed"
    | "#7dd3fc"
    | "#7e22ce"
    | "#7f1d1d"
    | "#800000"
    | "#818cf8"
    | "#831843"
    | "#84cc16"
    | "#854d0e"
    | "#86198f"
    | "#86efac"
    | "#881337"
    | "#8b5cf6"
    | "#92400e"
    | "#9333ea"
    | "#93c5fd"
    | "#94a3b8"
    | "#991b1b"
    | "#99f6e4"
    | "#9a3412"
    | "#9d174d"
    | "#9f1239"
    | "#a16207"
    | "#a21caf"
    | "#a3e635"
    | "#a5b4fc"
    | "#a5f3fc"
    | "#a78bfa"
    | "#a7f3d0"
    | "#a855f7"
    | "#b45309"
    | "#b91c1c"
    | "#bae6fd"
    | "#bbf7d0"
    | "#be123c"
    | "#be185d"
    | "#bef264"
    | "#bfdbfe"
    | "#c026d3"
    | "#c084fc"
    | "#c2410c"
    | "#c4b5fd"
    | "#c7d2fe"
    | "#ca8a04"
    | "#cbd5e1"
    | "#ccfbf1"
    | "#cffafe"
    | "#d1fae5"
    | "#d8b4fe"
    | "#d946ef"
    | "#d97706"
    | "#d9f99d"
    | "#db2777"
    | "#dbeafe"
    | "#dc2626"
    | "#dcfce7"
    | "#ddd6fe"
    | "#e0e7ff"
    | "#e0f2fe"
    | "#e11d48"
    | "#e2e8f0"
    | "#e879f9"
    | "#e9d5ff"
    | "#ea580c"
    | "#eab308"
    | "#ec4899"
    | "#ecfccb"
    | "#ecfdf5"
    | "#ecfeff"
    | "#ede9fe"
    | "#eef2ff"
    | "#ef4444"
    | "#eff6ff"
    | "#f0abfc"
    | "#f0f9ff"
    | "#f0fdf4"
    | "#f0fdfa"
    | "#f1f5f9"
    | "#f3e8ff"
    | "#f43f5e"
    | "#f472b6"
    | "#f59e0b"
    | "#f5d0fe"
    | "#f5f3ff"
    | "#f7fee7"
    | "#f87171"
    | "#f8fafc"
    | "#f97316"
    | "#f9a8d4"
    | "#facc15"
    | "#fae8ff"
    | "#faf5ff"
    | "#fb7185"
    | "#fb923c"
    | "#fbbf24"
    | "#fbcfe8"
    | "#fca5a5"
    | "#fcd34d"
    | "#fce7f3"
    | "#fda4af"
    | "#fdba74"
    | "#fde047"
    | "#fde68a"
    | "#fdf2f8"
    | "#fdf4ff"
    | "#fecaca"
    | "#fecdd3"
    | "#fed7aa"
    | "#fee2e2"
    | "#fef08a"
    | "#fef2f2"
    | "#fef3c7"
    | "#fef9c3"
    | "#fefce8"
    | "#ffe4e6"
    | "#ffedd5"
    | "#fff1f2"
    | "#fff7ed"
    | "#fffbeb";
} | null;

// Source: ./sanity/lib/sales/getAllActiveSales.ts
// Variable: GET_ACTIVE_SALES_QUERY
// Query: *[_type == "sale" && isActive == true] {        _id,        title,        "slug": slug.current,        discount,        validFrom,        validUntil,        isActive      }
export type GET_ACTIVE_SALES_QUERYResult = Array<never>;

// Source: ./sanity/lib/sales/getSaleByID.ts
// Variable: SALE_BY_ID_QUERY
// Query: *[_type == "sale" && _id == $saleId]{      name,      "slug": slug.current,      validFrom,      validUntil,      isActive,      description,      "image": image.asset->url,      category->{        name,        "slug": slug.current,        "products": *[_type=='product' && categoryPath == ^.metadata.path]{          name,          "slug": slug.current,          image,          defaultPrice        }      }    }
export type SALE_BY_ID_QUERYResult = Array<never>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "commercial" && feature == "hero-main" && defined(image.asset)]\n  | order(displayOrder asc) [0]\n  {\n    _id,\n    "image": image.asset->url + "?fm=webp&w=1200&q=55",\n    "blurDataURL": image.asset->url + "?w=20&h=20&blur=10&q=20",\n    text,\n    ctaLink,\n    sale-> {\n      discount,\n      validUntil,\n      _id\n    }\n  }': GET_COMMERCIALS_HERO_MAINResult;
    '*[_type == "commercial" && feature == $feature] | order(displayOrder asc) {\n    _id,\n    title,\n    "image": image.asset->url,\n    variant,\n    displayOrder,\n    text,\n    ctaLink,\n    "products": products[]-> {\n      _id,\n      brand,\n      name,\n      description,\n      price,\n      "image": image.asset->url,\n    },\n    sale-> {\n      discount,\n      validUntil,\n      _id\n    }\n  }': GET_COMMERCIALS_BY_FEATURE_QUERYResult;
    '*[_type == "commercial" && feature == "hero-secondary" && defined(image.asset)] | order(displayOrder asc) {\n    _id,\n    title,\n    "image": image.asset->url,\n    variant,\n    displayOrder,\n    text,\n    ctaLink,\n    "products": products[]-> {\n      _id,\n      brand,\n      name,\n      description,\n      price,\n      "image": image.asset->url,\n    },\n    sale-> {\n      discount,\n      validUntil,\n      _id\n    }\n  }': GET_COMMERCIALS_HERO_SECONDARYResult;
    '{\n    "brands": array::unique(*[_type == "product"].brand->name)\n  }': FILTERSResult;
    '\n    *[_type == "categoryFilters" && title == $topLevelCategory][0] {\n      title,\n      "filters": filters.filterItems[]{\n        name,\n        type,\n        options,\n        defaultValue,\n        min,\n        max,\n        isMinOnly,\n        step\n      },\n      "mappings": categoryMappings[path == $cleanPath]\n    }\n  ': FILTERS_BY_CATEGORY_QUERYResult;
    '\n        *[\n            _type == "product"\n        ] | order(name asc)\n    ': ALL_PRODUCTS_QUERYResult;
    "\n            *[\n                _type == 'product'\n                && _id == $id\n            ] | order(name asc) [0]\n        ": PRODUCT_BY_ID_QUERYResult;
    '*[\n        _type == "product"\n        && name match $searchParam\n    ] | order(name asc)': SEARCH_FOR_PRODUCTS_QUERYResult;
    '\n    *[_type == "categorySortables" && title == $topLevelCategory][0] {\n      title,\n      "sortOptions": sortOptions[]{\n        name,\n        displayName,\n        type,\n        field,\n        defaultDirection\n      },\n      "mappings": categoryMappings[path == $cleanPath]\n    }\n  ': SORTABLES_BY_CATEGORY_QUERYResult;
    '\n    *[_type == "userProfile" && clerkId == $clerkId][0] {\n      _id,\n      _type,\n      clerkId,\n      displayName,\n      primaryAddress {\n        streetAddress,\n        city,\n        state,\n        postalCode,\n        country\n      },\n      preferences {\n        receiveMarketingEmails,\n        darkMode,\n        savePaymentInfo\n      },\n      createdAt,\n      updatedAt\n    }\n  ': FETCH_PROFILE_QUERYResult;
    '\n    *[_type == "promotion" && internalTitle == $name][0]  {\n      _id,\n     promotion_text,\n        cta_text,\n        cta_background,\n      "image_background": {\n        "src": image_background.asset->url,\n        "alt": image_background.alt,\n        "width": image_background.asset->metadata.dimensions.width,\n        "height": image_background.asset->metadata.dimensions.height,\n        "blurDataURL": image_background.asset->metadata.lqip\n      }\n    }\n  ': PROMOTION_BY_NAME_QUERYResult;
    '\n    *[_type == "promotion"][0]\n  ': SMALL_TESTResult;
    '\n      *[_type == "sale" && isActive == true] {\n        _id,\n        title,\n        "slug": slug.current,\n        discount,\n        validFrom,\n        validUntil,\n        isActive\n      }\n    ': GET_ACTIVE_SALES_QUERYResult;
    '\n    *[_type == "sale" && _id == $saleId]{\n      name,\n      "slug": slug.current,\n      validFrom,\n      validUntil,\n      isActive,\n      description,\n      "image": image.asset->url,\n      category->{\n        name,\n        "slug": slug.current,\n        "products": *[_type==\'product\' && categoryPath == ^.metadata.path]{\n          name,\n          "slug": slug.current,\n          image,\n          defaultPrice\n        }\n      }\n    }\n  ': SALE_BY_ID_QUERYResult;
  }
}
