import type { Address } from "@/features/address";

// Every addressKey in storage was generated by randomUUID() below. Rejecting
// anything else before it reaches a Sanity patch path expression closes off
// path injection via a tampered hidden form field.
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isValidAddressKey(key: string): boolean {
  return UUID_RE.test(key);
}

export function parseAddress(formData: FormData): Address | { error: string } {
  const firstName = (formData.get("firstName") as string)?.trim();
  const lastName = (formData.get("lastName") as string)?.trim();
  const phone = (formData.get("phone") as string)?.trim();
  const regionCode = (formData.get("regionCode") as string)?.trim();
  const postalCode = (formData.get("postalCode") as string)?.trim();
  const street = (formData.get("street") as string)?.trim();
  const streetNumber = (formData.get("streetNumber") as string)?.trim();
  const city = (formData.get("city") as string)?.trim();

  if (
    !firstName ||
    !lastName ||
    !phone ||
    !regionCode ||
    !postalCode ||
    !street ||
    !streetNumber ||
    !city
  ) {
    return { error: "All fields are required." };
  }

  return {
    firstName,
    lastName,
    phone,
    regionCode,
    postalCode,
    street,
    streetNumber,
    city,
  };
}
