import plugin from "tailwindcss/plugin";

export const typographyDefaultsPlugin = plugin(function ({ addUtilities }) {
  addUtilities({
    ".text-cap": {
      "text-box": "trim-both cap alphabetic",
    },
    ".text-ex": {
      "text-box": "trim-both ex alphabetic",
    },
  });
});

export const uiComponentsPlugin = plugin(function ({ addComponents, theme }) {
  addComponents({
    ".btn-primary": {
      backgroundColor: theme("colors.brand.400") as string,
      color: theme("colors.brand.700") as string,
      fontWeight: theme("fontWeight.bold") as string,
      borderRadius: theme("borderRadius.md") as string,
      boxShadow: theme("boxShadow.button") as string,
      transition: "background-color 0.2s ease, box-shadow 0.2s ease",
      "&:hover": {
        backgroundColor: theme("colors.brand.500") as string,
        boxShadow: theme("boxShadow.buttonHover") as string,
      },
      "&:focus-visible": {
        outline: `2px solid ${theme("colors.brand.600")}`,
        outlineOffset: "2px",
      },
      "&:active": {
        backgroundColor: theme("colors.brand.600") as string,
      },
      "&:disabled": {
        opacity: "0.4",
        cursor: "not-allowed",
      },
    },
    ".btn-cart": {
      display: "inline-flex",
      alignItems: "center",
      gap: theme("spacing.2") as string,
      backgroundColor: theme("colors.accent.500") as string,
      color: theme("colors.brand.700") as string,
      fontWeight: theme("fontWeight.bold") as string,
      fontSize: theme("fontSize.action[0]") as string,
      lineHeight: theme("fontSize.action[1].lineHeight") as string,
      padding: `${theme("spacing.2")} ${theme("spacing.2")}`,
      borderRadius: theme("borderRadius.sm") as string,
      boxShadow: theme("boxShadow.button") as string,
      transition: "background-color 0.2s ease, box-shadow 0.2s ease",
      "@media (max-width: 767px)": {
        gap: theme("spacing.1") as string,
        fontSize: theme("fontSize.tiny[0]") as string,
        lineHeight: "1",
        padding: `${theme("spacing.1")} ${theme("spacing.2")}`,
      },
      "&:hover": {
        backgroundColor: theme("colors.accent.600") as string,
        boxShadow: theme("boxShadow.buttonHover") as string,
      },
      "&:focus-visible": {
        outline: `2px solid ${theme("colors.accent.600")}`,
        outlineOffset: "2px",
      },
      "&:active": {
        backgroundColor: theme("colors.accent.600") as string,
      },
      "&:disabled": {
        opacity: "0.4",
        cursor: "not-allowed",
      },
    },
    ".btn-product-add": {
      display: "inline-flex",
      alignItems: "center",
      gap: "6px",
      backgroundColor: theme("colors.accent.500") as string,
      color: theme("colors.brand.700") as string,
      fontWeight: theme("fontWeight.semibold") as string,
      fontSize: "12px",
      lineHeight: "1",
      padding: "7px 10px",
      borderRadius: theme("borderRadius.sm") as string,
      boxShadow: theme("boxShadow.button") as string,
      transition: "background-color 0.2s ease, box-shadow 0.2s ease",
      "&:hover": {
        backgroundColor: theme("colors.accent.600") as string,
        boxShadow: theme("boxShadow.buttonHover") as string,
      },
      "&:focus-visible": {
        outline: `2px solid ${theme("colors.accent.600")}`,
        outlineOffset: "2px",
      },
      "&:active": {
        backgroundColor: theme("colors.accent.600") as string,
      },
      "&:disabled": {
        opacity: "0.4",
        cursor: "not-allowed",
      },
    },
    ".btn-cart-large": {
      display: "inline-flex",
      WebkitFontSmoothing: "antialiased",
      MozOsxFontSmoothing: "grayscale",
      alignItems: "center",
      gap: theme("spacing.4") as string,
      backgroundColor: theme("colors.accent.500") as string,
      color: theme("colors.brand.700") as string,
      fontWeight: theme("fontWeight.bold") as string,
      fontSize: theme("fontSize.actionLarge[0]") as string,
      lineHeight: theme("fontSize.actionLarge[1].lineHeight") as string,
      padding: `${theme("spacing.4")} ${theme("spacing.8")}`,
      borderRadius: theme("borderRadius.sm") as string,
      boxShadow: theme("boxShadow.button") as string,
      transition: "background-color 0.2s ease, box-shadow 0.2s ease",
      "&:hover": {
        backgroundColor: theme("colors.accent.600") as string,
        boxShadow: theme("boxShadow.buttonHover") as string,
      },
      "&:focus-visible": {
        outline: `2px solid ${theme("colors.accent.600")}`,
        outlineOffset: "2px",
      },
      "&:active": {
        backgroundColor: theme("colors.accent.600") as string,
      },
      "&:disabled": {
        opacity: "0.4",
        cursor: "not-allowed",
      },
    },
    ".btn-stepper": {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      width: theme("spacing.11") as string,
      height: theme("spacing.11") as string,
      minWidth: theme("spacing.11") as string,
      minHeight: theme("spacing.11") as string,
      backgroundColor: theme("colors.surface.elevated") as string,
      border: `1px solid ${theme("colors.border.secondary")}`,
      color: theme("colors.text.secondary") as string,
      transition: "background-color 0.2s ease, border-color 0.2s ease, color 0.2s ease",
      "&:hover": {
        borderColor: theme("colors.border.primary") as string,
        color: theme("colors.text.primary") as string,
      },
      "&:focus-visible": {
        outline: `2px solid ${theme("colors.accent.600")}`,
        outlineOffset: "2px",
      },
      "&:disabled": {
        opacity: "0.3",
        cursor: "not-allowed",
      },
    },
    ".btn-stepper-sm": {
      width: theme("spacing.9") as string,
      height: theme("spacing.9") as string,
      minWidth: theme("spacing.9") as string,
      minHeight: theme("spacing.9") as string,
    },
    ".btn-in-basket-large": {
      display: "inline-flex antialiased",
      alignItems: "center",
      gap: theme("spacing.4") as string,
      backgroundColor: theme("colors.success.700") as string,
      color: theme("colors.brand.50") as string,
      fontWeight: theme("fontWeight.bold") as string,
      fontSize: theme("fontSize.actionLarge[0]") as string,
      lineHeight: theme("fontSize.actionLarge[1].lineHeight") as string,
      padding: `${theme("spacing.4")} ${theme("spacing.4")}`,
      borderRadius: theme("borderRadius.sm") as string,
      boxShadow: theme("boxShadow.button") as string,
      transition: "background-color 0.2s ease, box-shadow 0.2s ease",
      "&:hover": {
        backgroundColor: theme("colors.success.800") as string,
        boxShadow: theme("boxShadow.buttonHover") as string,
        cursor: "default",
      },
      "&:focus-visible": {
        outline: `2px solid ${theme("colors.success.700")}`,
        outlineOffset: "2px",
      },
      "&:active": {
        backgroundColor: theme("colors.success.700") as string,
      },
      "&:disabled": {
        opacity: "1",
      },
    },
    ".btn-secondary": {
      backgroundColor: "transparent",
      border: `1px solid ${theme("colors.brand.200")}`,
      color: theme("colors.brand.100") as string,
      borderRadius: theme("borderRadius.md") as string,
      transition: "all 0.2s ease",
      "&:hover": {
        backgroundColor: theme("colors.brand.300") as string,
        color: theme("colors.brand.700") as string,
      },
      "&:active": {
        backgroundColor: theme("colors.brand.500") as string,
      },
    },
    ".btn-ghost": {
      backgroundColor: "transparent",
      border: "none",
      color: theme("colors.brand.400") as string,
      fontWeight: theme("fontWeight.light") as string,
      fontSize: theme("fontSize.cta-hero[0]") as string,
      lineHeight: theme("fontSize.cta-hero[1].lineHeight") as string,
      letterSpacing: theme("letterSpacing.editorial") as string,
      textTransform: "uppercase",
      textDecoration: "underline",
      textUnderlineOffset: "9px",
      borderRadius: theme("borderRadius.sm") as string,
      transition: "color 0.2s ease",
      "&:hover": {
        color: theme("colors.brand.100") as string,
      },
      "&:focus-visible": {
        outline: `2px solid ${theme("colors.brand.100")}`,
        outlineOffset: "2px",
      },
    },
    ".card-base": {
      backgroundColor: theme("colors.surface.card") as string,
      padding: theme("spacing.6") as string,
      borderRadius: theme("borderRadius.lg") as string,
      boxShadow: theme("boxShadow.card") as string,
      border: `1px solid ${theme("colors.border.secondary")}`,
    },
    ".card-product": {
      backgroundColor: "transparent",
      padding: theme("spacing.6") as string,
      borderRadius: theme("borderRadius.lg") as string,
      boxShadow: theme("boxShadow.card") as string,
      border: `1px solid ${theme("colors.border.secondary")}`,
      transition: "box-shadow 0.3s ease, transform 0.3s ease",
      "&:hover": {
        boxShadow: theme("boxShadow.cardHover") as string,
        transform: "translateY(-2px)",
      },
    },
    ".card-product-dark": {
      backgroundColor: "transparent",
      padding: theme("spacing.6") as string,
      borderRadius: theme("borderRadius.lg") as string,
      boxShadow: theme("boxShadow.cardDark") as string,
      border: `1px solid ${theme("colors.border.secondary")}`,
      transition: "all 300ms ease-out",
      "&:hover": {
        boxShadow: theme("boxShadow.cardHoverDark") as string,
        borderColor: theme("colors.brand.400") as string,
        transform: "translateY(-2px)",
      },
    },
    ".input-base": {
      backgroundColor: theme("colors.surface.elevated") as string,
      border: `1px solid ${theme("colors.border.primary")}`,
      borderRadius: theme("borderRadius.md") as string,
      padding: `${theme("spacing.3")} ${theme("spacing.4")}`,
      fontSize: theme("fontSize.body[0]") as string,
      lineHeight: theme("fontSize.body[1].lineHeight") as string,
      fontWeight: theme("fontWeight.regular") as string,
      color: theme("colors.text.body") as string,
      transition: "border-color 0.2s ease, box-shadow 0.2s ease",
      "&::placeholder": {
        color: theme("colors.text.caption") as string,
      },
      "&:focus-visible": {
        outline: `2px solid ${theme("colors.brand.600")}`,
        outlineOffset: "2px",
        borderColor: theme("colors.brand.400") as string,
      },
      "&:disabled": {
        opacity: "0.4",
        cursor: "not-allowed",
        backgroundColor: theme("colors.surface.subtle") as string,
      },
    },
    ".input-field": {
      backgroundColor: theme("colors.surface.elevated") as string,
      border: `1px solid ${theme("colors.border.primary")}`,
      borderRadius: theme("borderRadius.md") as string,
      padding: `${theme("spacing.3")} ${theme("spacing.4")}`,
      fontSize: theme("fontSize.body[0]") as string,
      lineHeight: theme("fontSize.body[1].lineHeight") as string,
      fontWeight: theme("fontWeight.regular") as string,
      color: theme("colors.text.body") as string,
      width: "100%",
      transition: "border-color 0.2s ease, box-shadow 0.2s ease",
      "&::placeholder": {
        color: theme("colors.text.caption") as string,
      },
      "&:focus-visible": {
        outline: `2px solid ${theme("colors.brand.600")}`,
        outlineOffset: "2px",
        borderColor: theme("colors.brand.400") as string,
      },
      "&:disabled": {
        opacity: "0.4",
        cursor: "not-allowed",
        backgroundColor: theme("colors.surface.subtle") as string,
      },
    },
    ".input-select": {
      backgroundColor: theme("colors.surface.elevated") as string,
      border: `1px solid ${theme("colors.border.primary")}`,
      borderRadius: theme("borderRadius.md") as string,
      padding: `${theme("spacing.3")} ${theme("spacing.4")}`,
      fontSize: theme("fontSize.body[0]") as string,
      lineHeight: theme("fontSize.body[1].lineHeight") as string,
      fontWeight: theme("fontWeight.regular") as string,
      color: theme("colors.text.body") as string,
      appearance: "none",
      backgroundImage: `url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3e%3cpath stroke='%23${(theme("colors.text.body") as string).slice(1)}' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M6 8l4 4 4-4'/%3e%3c/svg%3e")`,
      backgroundPosition: `right ${theme("spacing.3")} center`,
      backgroundRepeat: "no-repeat",
      backgroundSize: "1.5em 1.5em",
      paddingRight: `calc(${theme("spacing.4")} + 1.5em)`,
      transition: "border-color 0.2s ease, box-shadow 0.2s ease",
      "&::placeholder": {
        color: theme("colors.text.caption") as string,
      },
      "&:focus-visible": {
        outline: `2px solid ${theme("colors.brand.600")}`,
        outlineOffset: "2px",
        borderColor: theme("colors.brand.400") as string,
      },
      "&:disabled": {
        opacity: "0.4",
        cursor: "not-allowed",
        backgroundColor: theme("colors.surface.subtle") as string,
      },
    },
    ".type-hero-headline": {
      fontSize: theme("fontSize.display-1[0]") as string,
      lineHeight: theme("fontSize.display-1[1].lineHeight") as string,
      letterSpacing: theme("fontSize.display-1[1].letterSpacing") as string,
      fontWeight: theme("fontWeight.bold") as string,
      color: theme("colors.text.heroHeadline") as string,
    },
    ".type-hero-sub": {
      fontSize: theme("fontSize.h2[0]") as string,
      lineHeight: theme("fontSize.h2[1].lineHeight") as string,
      letterSpacing: theme("fontSize.h2[1].letterSpacing") as string,
      fontWeight: theme("fontWeight.medium") as string,
      color: theme("colors.text.heroSubHeadline") as string,
    },
    ".type-section-caption": {
      fontSize: theme("fontSize.small[0]") as string,
      lineHeight: theme("fontSize.small[1].lineHeight") as string,
      letterSpacing: theme("letterSpacing.editorial") as string,
      fontWeight: theme("fontWeight.light") as string,
      color: theme("colors.text.caption") as string,
    },
    ".type-section-hed": {
      fontSize: theme("fontSize.h1[0]") as string,
      lineHeight: theme("fontSize.h1[1].lineHeight") as string,
      letterSpacing: theme("fontSize.h1[1].letterSpacing") as string,
      fontWeight: theme("fontWeight.semibold") as string,
      color: theme("colors.text.headline") as string,
    },
    ".type-section-sub": {
      fontSize: theme("fontSize.h2[0]") as string,
      lineHeight: theme("fontSize.h2[1].lineHeight") as string,
      letterSpacing: theme("fontSize.h2[1].letterSpacing") as string,
      fontWeight: theme("fontWeight.medium") as string,
      color: theme("colors.text.subtitle") as string,
    },
    ".type-card-title": {
      fontSize: theme("fontSize.body[0]") as string,
      lineHeight: theme("fontSize.body[1].lineHeight") as string,
      letterSpacing: theme("fontSize.body[1].letterSpacing") as string,
      fontWeight: theme("fontWeight.semibold") as string,
      color: theme("colors.text.body") as string,
    },
    ".type-product-brand": {
      fontSize: "10px",
      lineHeight: "14px",
      letterSpacing: "0.08em",
      textTransform: "uppercase",
      fontWeight: theme("fontWeight.medium") as string,
      color: theme("colors.text.caption") as string,
    },
    ".type-product-title": {
      fontSize: "13px",
      lineHeight: "1.4",
      letterSpacing: "0em",
      fontWeight: theme("fontWeight.medium") as string,
      color: theme("colors.text.body") as string,
    },
    ".type-product-price": {
      fontSize: "14px",
      lineHeight: "1.4",
      letterSpacing: "0em",
      fontWeight: theme("fontWeight.semibold") as string,
      fontVariantNumeric: "tabular-nums",
      color: theme("colors.text.priceTag") as string,
    },
    ".type-metadata": {
      fontSize: theme("fontSize.h4[0]") as string,
      lineHeight: theme("fontSize.h4[1].lineHeight") as string,
      letterSpacing: theme("fontSize.h4[1].letterSpacing") as string,
      fontWeight: theme("fontWeight.medium") as string,
      color: theme("colors.text.secondary") as string,
    },
    ".type-price": {
      fontSize: theme("fontSize.h4[0]") as string,
      lineHeight: theme("fontSize.h4[1].lineHeight") as string,
      letterSpacing: theme("fontSize.h4[1].letterSpacing") as string,
      fontWeight: theme("fontWeight.semibold") as string,
      color: theme("colors.text.priceTag") as string,
    },
    ".type-overline": {
      fontSize: theme("fontSize.small[0]") as string,
      lineHeight: theme("fontSize.small[1].lineHeight") as string,
      letterSpacing: theme("letterSpacing.editorial") as string,
      fontWeight: theme("fontWeight.light") as string,
      textTransform: "uppercase",
      color: theme("colors.text.overline") as string,
    },
    ".type-body": {
      fontSize: theme("fontSize.body[0]") as string,
      lineHeight: theme("fontSize.body[1].lineHeight") as string,
      letterSpacing: theme("fontSize.body[1].letterSpacing") as string,
      fontWeight: theme("fontWeight.regular") as string,
      color: theme("colors.text.body") as string,
    },
    ".type-caption": {
      fontSize: theme("fontSize.small[0]") as string,
      lineHeight: theme("fontSize.small[1].lineHeight") as string,
      letterSpacing: theme("fontSize.small[1].letterSpacing") as string,
      fontWeight: theme("fontWeight.regular") as string,
      color: theme("colors.text.body") as string,
    },
    ".product-badge": {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: theme("fontSize.tiny[0]") as string,
      lineHeight: theme("fontSize.tiny[1].lineHeight") as string,
      fontWeight: theme("fontWeight.light") as string,
      letterSpacing: theme("letterSpacing.editorial") as string,
      textTransform: "uppercase",
      whiteSpace: "nowrap",
      padding: `${theme("spacing.0.5")} ${theme("spacing.2")}`,
      borderRadius: theme("borderRadius.sm") as string,
      backgroundColor: theme("colors.brand.900") as string,
      color: theme("colors.brand.50") as string,
    },
    ".section-header-anchor": {
      display: "flex",
      alignItems: "center",
      gap: theme("spacing.3") as string,
      "&::before": {
        content: '""',
        display: "block",
        width: "32px",
        height: "1px",
        backgroundColor: theme("colors.brand.400") as string,
        flexShrink: "0",
      },
    },
  });
});
