"use server";

import { requireSession } from "@/lib/auth/dal";
import { auth } from "@/lib/auth/server";
import { getProfileIdByAuthId } from "@/sanity-cms/lib/account/getProfileIdByAuthId";
import { headers } from "next/headers";
import { randomUUID } from "node:crypto";
import type { Address } from "@/features/checkout";
import { setProfileName } from "@/sanity-cms/lib/account/setProfileName";
import { setMarketingOptIn } from "@/sanity-cms/lib/account/setMarketingOptIn";
import { addProfileAddress } from "@/sanity-cms/lib/account/addProfileAddress";
import { replaceProfileAddress } from "@/sanity-cms/lib/account/replaceProfileAddress";
import { removeProfileAddress } from "@/sanity-cms/lib/account/removeProfileAddress";

export async function updateName(formData: FormData) {
  const session = await requireSession();
  const name = (formData.get("name") as string)?.trim();
  if (!name) return { error: "Name cannot be empty." };

  await auth.api.updateUser({
    headers: await headers(),
    body: { name },
  });

  const profile = await getProfileIdByAuthId(session.userId);
  if (profile?._id) {
    await setProfileName(profile._id, name);
  }

  return { success: true, name };
}

export async function updatePreferences(formData: FormData) {
  const session = await requireSession();
  const marketingEmailsOptIn = formData.get("marketingEmailsOptIn") === "on";

  const profile = await getProfileIdByAuthId(session.userId);
  if (!profile?._id) {
    return { error: "Profile not found." };
  }

  await setMarketingOptIn(profile._id, marketingEmailsOptIn);

  return { success: true, marketingEmailsOptIn };
}

// Every addressKey in storage was generated by randomUUID() below. Rejecting
// anything else before it reaches a Sanity patch path expression closes off
// path injection via a tampered hidden form field.
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

function isValidAddressKey(key: string): boolean {
  return UUID_RE.test(key);
}

function parseAddress(formData: FormData): Address | { error: string } {
  const firstName = (formData.get("firstName") as string)?.trim();
  const lastName = (formData.get("lastName") as string)?.trim();
  const phone = (formData.get("phone") as string)?.trim();
  const regionCode = (formData.get("regionCode") as string)?.trim();
  const postalCode = (formData.get("postalCode") as string)?.trim();
  const street = (formData.get("street") as string)?.trim();
  const streetNumber = (formData.get("streetNumber") as string)?.trim();
  const city = (formData.get("city") as string)?.trim();

  if (
    !firstName ||
    !lastName ||
    !phone ||
    !regionCode ||
    !postalCode ||
    !street ||
    !streetNumber ||
    !city
  ) {
    return { error: "All fields are required." };
  }

  return {
    firstName,
    lastName,
    phone,
    regionCode,
    postalCode,
    street,
    streetNumber,
    city,
  };
}

export async function addAddress(formData: FormData) {
  const session = await requireSession();
  const parsed = parseAddress(formData);
  if ("error" in parsed) return parsed;

  const profile = await getProfileIdByAuthId(session.userId);
  if (!profile?._id) {
    return { error: "Profile not found." };
  }

  const newAddress = { _key: randomUUID(), ...parsed };

  await addProfileAddress(profile._id, newAddress);

  return { success: true };
}

export async function updateAddress(addressKey: string, formData: FormData) {
  const session = await requireSession();
  if (!isValidAddressKey(addressKey)) return { error: "Invalid address." };

  const parsed = parseAddress(formData);
  if ("error" in parsed) return parsed;

  const profile = await getProfileIdByAuthId(session.userId);
  if (!profile?._id) {
    return { error: "Profile not found." };
  }

  const updatedAddress = { _key: addressKey, ...parsed };

  await replaceProfileAddress(profile._id, addressKey, updatedAddress);

  return { success: true };
}

export async function removeAddress(addressKey: string) {
  const session = await requireSession();
  if (!isValidAddressKey(addressKey)) return { error: "Invalid address." };

  const profile = await getProfileIdByAuthId(session.userId);
  if (!profile?._id) {
    return { error: "Profile not found." };
  }

  await removeProfileAddress(profile._id, addressKey);

  return { success: true };
}
